nodes:
  # Wazuh indexer nodes
  indexer:
    - name: node-1
      ip: "172.23.128.164"
    #- name: node-2
    #  ip: "172.23.128.164"
    #- name: node-3
    #  ip: "172.23.128.164"

  # Wazuh server nodes
  # If there is more than one Wazuh server
  # node, each one must have a node_type
  server:
    - name: wazuh-1
      ip: "172.23.128.164"
    #  node_type: master
    #- name: wazuh-2
    #  ip: "172.23.128.164"
    #  node_type: worker
    #- name: wazuh-3
    #  ip: "172.23.128.164"
    #  node_type: worker

  # Wazuh dashboard nodes
  dashboard:
    - name: dashboard
      ip: "172.23.128.164"

#please replace the above with your OWN IPs or Localhost address
